// ───────────────────────────────────────────────────────────────────────────
//  EkkoJS · Pure ESM JavaScript & TypeScript runtime
//
//  License      MIT
//  Copyright    © 2026 Ampla Network LLC
//  Contact      hello@e-mc2.dev
//
//  EkkoJS is the result of the whole team's effort. Enjoy using it!
// ───────────────────────────────────────────────────────────────────────────

use crate::parser::ExportedMethod;
use crate::types;

pub fn generate_module(methods: &[ExportedMethod], _mod_name: &str) -> String {
    let sync_methods: Vec<&ExportedMethod> = methods.iter().filter(|m| !m.is_async).collect();
    let async_methods: Vec<&ExportedMethod> = methods.iter().filter(|m| m.is_async).collect();
    let has_async = !async_methods.is_empty();
    let mut out = String::new();

    out.push_str("// AUTO-GENERATED by ekko-bindgen — do not edit\n");
    out.push_str("#![allow(non_snake_case, unused_imports)]\n");
    out.push_str("#![allow(dead_code)]\n\n");
    out.push_str("use std::ffi::CStr;\n");
    if has_async {
        out.push_str("use tokio::sync::oneshot;\n");
        out.push_str("use std::sync::Mutex;\n");
        out.push_str("use std::sync::atomic::{AtomicI64, Ordering};\n");
        out.push_str("use std::collections::HashMap;\n");
    }
    out.push('\n');
    out.push_str(&generate_native_types());
    out.push('\n');
    if has_async {
        out.push_str(&generate_async_callback());
        out.push('\n');
    }
    out.push_str(&generate_api_struct(&sync_methods, &async_methods));
    out.push('\n');
    out.push_str(&generate_api_impl(&sync_methods, &async_methods));

    out
}

fn generate_native_types() -> String {
    r#"#[repr(C)]
#[derive(Clone, Copy)]
pub struct NativeString {
    pub ptr: *mut u8,
    pub len: i32,
}

impl NativeString {
    pub fn to_string_lossy(&self) -> String {
        if self.ptr.is_null() || self.len <= 0 || self.len > 0x7FFF_0000 {
            return String::new();
        }
        unsafe {
            let slice = std::slice::from_raw_parts(self.ptr, self.len as usize);
            String::from_utf8_lossy(slice).to_string()
        }
    }

    pub fn from_str(s: &str) -> Self {
        let bytes = s.as_bytes();
        if bytes.is_empty() {
            return Self { ptr: std::ptr::null_mut(), len: 0 };
        }
        let len = i32::try_from(bytes.len()).expect("NativeString: string too large for i32 len");
        let ptr = unsafe {
            let layout = std::alloc::Layout::from_size_align(bytes.len(), 1).unwrap();
            let p = std::alloc::alloc(layout);
            if p.is_null() { std::alloc::handle_alloc_error(layout); }
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), p, bytes.len());
            p
        };
        Self { ptr, len }
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct NativeBuffer {
    pub ptr: *mut u8,
    pub len: i32,
}

impl NativeBuffer {
    pub fn to_vec(&self) -> Vec<u8> {
        if self.ptr.is_null() || self.len <= 0 || self.len > 0x7FFF_0000 {
            return Vec::new();
        }
        unsafe { std::slice::from_raw_parts(self.ptr, self.len as usize).to_vec() }
    }
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct NativeResult {
    pub is_ok: u8,
    pub int_value: i64,
    pub float_value: f64,
    pub string_value: NativeString,
    pub buffer_value: NativeBuffer,
    pub error_code: NativeString,
    pub error_message: NativeString,
    pub handle_value: i32,
}

unsafe impl Send for NativeString {}
unsafe impl Send for NativeBuffer {}
unsafe impl Send for NativeResult {}
"#
    .to_string()
}

fn generate_async_callback() -> String {
    r#"static NEXT_CB_ID: AtomicI64 = AtomicI64::new(1);
static CB_REGISTRY: Mutex<Option<HashMap<i64, oneshot::Sender<NativeResult>>>> = Mutex::new(None);

fn register_callback(tx: oneshot::Sender<NativeResult>) -> i64 {
    let id = NEXT_CB_ID.fetch_add(1, Ordering::Relaxed);
    let mut guard = CB_REGISTRY.lock().unwrap();
    guard.get_or_insert_with(HashMap::new).insert(id, tx);
    id
}

extern "C" fn async_completion(result: NativeResult, context: i64) {
    let tx = {
        let mut guard = CB_REGISTRY.lock().unwrap();
        guard.as_mut().and_then(|m| m.remove(&context))
    };
    if let Some(tx) = tx {
        let _ = tx.send(result);
    }
}
"#
    .to_string()
}

fn generate_api_struct(sync_methods: &[&ExportedMethod], async_methods: &[&ExportedMethod]) -> String {
    let mut out = String::new();
    out.push_str("pub struct Api {\n");
    out.push_str("    _lib: libloading::Library,\n");

    for m in sync_methods {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        let params = ffi_param_types(m);
        out.push_str(&format!(
            "    {}: unsafe extern \"C\" fn({}) -> NativeResult,\n",
            c_symbol, params
        ));
    }

    for m in async_methods {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        let params = ffi_param_types(m);
        let sep = if params.is_empty() { "" } else { ", " };
        out.push_str(&format!(
            "    {}: unsafe extern \"C\" fn({}{}isize, i64),\n",
            c_symbol, params, sep
        ));
    }

    out.push_str("    free_string: unsafe extern \"C\" fn(NativeString),\n");
    out.push_str("    free_buffer: unsafe extern \"C\" fn(NativeBuffer),\n");
    out.push_str("}\n");
    out
}

fn generate_api_impl(sync_methods: &[&ExportedMethod], async_methods: &[&ExportedMethod]) -> String {
    let mut out = String::new();

    out.push_str("impl Api {\n");
    out.push_str("    pub fn load(lib: libloading::Library) -> Result<Self, String> {\n");
    out.push_str("        let (\n");
    for m in sync_methods.iter().chain(async_methods.iter()) {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        out.push_str(&format!("            {},\n", c_symbol));
    }
    out.push_str("            free_string,\n");
    out.push_str("            free_buffer,\n");
    out.push_str("        ) = unsafe {\n");

    for m in sync_methods {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        out.push_str(&format!(
            "            let s: libloading::Symbol<unsafe extern \"C\" fn({params}) -> NativeResult> = lib.get(b\"{c}\").map_err(|e| e.to_string())?;\n",
            c = c_symbol,
            params = ffi_param_types(m),
        ));
        out.push_str(&format!(
            "            let {} = *s;\n",
            c_symbol
        ));
    }

    for m in async_methods {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        let params = ffi_param_types(m);
        let sep = if params.is_empty() { "" } else { ", " };
        out.push_str(&format!(
            "            let s: libloading::Symbol<unsafe extern \"C\" fn({}{}isize, i64)> = lib.get(b\"{}\").map_err(|e| e.to_string())?;\n",
            params, sep, c_symbol,
        ));
        out.push_str(&format!(
            "            let {} = *s;\n",
            c_symbol
        ));
    }

    out.push_str("            let s: libloading::Symbol<unsafe extern \"C\" fn(NativeString)> = lib.get(b\"ekko_native_free_string\").map_err(|e| e.to_string())?;\n");
    out.push_str("            let free_string = *s;\n");
    out.push_str("            let s: libloading::Symbol<unsafe extern \"C\" fn(NativeBuffer)> = lib.get(b\"ekko_native_free_buffer\").map_err(|e| e.to_string())?;\n");
    out.push_str("            let free_buffer = *s;\n");

    out.push_str("            (\n");
    for m in sync_methods.iter().chain(async_methods.iter()) {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        out.push_str(&format!("                {},\n", c_symbol));
    }
    out.push_str("                free_string,\n");
    out.push_str("                free_buffer,\n");
    out.push_str("            )\n");
    out.push_str("        };\n");
    out.push_str("        Ok(Self {\n");
    out.push_str("            _lib: lib,\n");
    for m in sync_methods.iter().chain(async_methods.iter()) {
        let c_symbol = types::export_name_to_c_symbol(&m.export_name);
        out.push_str(&format!("            {},\n", c_symbol));
    }
    out.push_str("            free_string,\n");
    out.push_str("            free_buffer,\n");
    out.push_str("        })\n");
    out.push_str("    }\n\n");

    for m in sync_methods {
        out.push_str(&generate_safe_method(m));
        out.push('\n');
    }

    for m in async_methods {
        out.push_str(&generate_async_safe_method(m));
        out.push('\n');
    }

    out.push_str("}\n");
    out
}

fn generate_safe_method(m: &ExportedMethod) -> String {
    let c_symbol = types::export_name_to_c_symbol(&m.export_name);
    let accessor = types::cs_return_to_rust_accessor(&m.return_type);
    let fn_name = m.export_name.replace('.', "_");

    let rust_params: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.cs_type.as_str() {
            "string" => format!("{}: &str", p.name),
            "byte[]" => format!("{}: &[u8]", p.name),
            "int" => format!("{}: i32", p.name),
            "long" => format!("{}: i64", p.name),
            "double" => format!("{}: f64", p.name),
            "bool" => format!("{}: bool", p.name),
            "nint" => format!("{}: isize", p.name),
            _ => format!("{}: &str", p.name),
        })
        .collect();

    let call_args: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.cs_type.as_str() {
            "string" => format!("NativeString::from_str({})", p.name),
            "byte[]" => format!("NativeBuffer {{ ptr: {name}.as_ptr() as *mut u8, len: i32::try_from({name}.len()).expect(\"buffer too large for i32\") }}", name = p.name),
            "bool" => format!("if {} {{ 1u8 }} else {{ 0u8 }}", p.name),
            "nint" => p.name.clone(),
            _ => p.name.clone(),
        })
        .collect();

    let return_type = match m.return_type.as_str() {
        "int" => "i32",
        "long" => "i64",
        "double" => "f64",
        "string" => "String",
        "byte[]" => "Vec<u8>",
        "bool" => "bool",
        "void" => "()",
        _ => "String",
    };

    let mut s = String::new();
    s.push_str(&format!(
        "    pub fn {}(&self, {}) -> Result<{}, String> {{\n",
        fn_name,
        rust_params.join(", "),
        return_type
    ));
    s.push_str("        unsafe {\n");
    s.push_str(&format!(
        "            let result = (self.{})({});\n",
        c_symbol,
        call_args.join(", ")
    ));
    s.push_str("            if result.is_ok == 0 {\n");
    s.push_str("                let msg = result.error_message.to_string_lossy();\n");
    s.push_str("                (self.free_string)(result.error_message);\n");
    s.push_str("                return Err(msg);\n");
    s.push_str("            }\n");

    match m.return_type.as_str() {
        "void" => s.push_str("            Ok(())\n"),
        "int" => s.push_str(&format!("            Ok(result.{} as i32)\n", accessor)),
        "long" => s.push_str(&format!("            Ok(result.{})\n", accessor)),
        "double" => s.push_str(&format!("            Ok(result.{})\n", accessor)),
        "bool" => s.push_str(&format!("            Ok(result.{} != 0)\n", accessor)),
        "byte[]" => {
            s.push_str("            let buf = result.buffer_value;\n");
            s.push_str("            let data = buf.to_vec();\n");
            s.push_str("            (self.free_buffer)(buf);\n");
            s.push_str("            Ok(data)\n");
        }
        "string" => {
            s.push_str(&format!(
                "            let s = result.{}.to_string_lossy();\n",
                accessor
            ));
            s.push_str(&format!(
                "            (self.free_string)(result.{});\n",
                accessor
            ));
            s.push_str("            Ok(s)\n");
        }
        _ => s.push_str("            Ok(())\n"),
    }

    s.push_str("        }\n");
    s.push_str("    }\n");
    s
}

fn generate_async_safe_method(m: &ExportedMethod) -> String {
    let c_symbol = types::export_name_to_c_symbol(&m.export_name);
    let accessor = types::cs_return_to_rust_accessor(&m.return_type);
    let fn_name = m.export_name.replace('.', "_");

    let rust_params: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.cs_type.as_str() {
            "string" => format!("{}: &str", p.name),
            "byte[]" => format!("{}: &[u8]", p.name),
            "int" => format!("{}: i32", p.name),
            "long" => format!("{}: i64", p.name),
            "double" => format!("{}: f64", p.name),
            "bool" => format!("{}: bool", p.name),
            "nint" => format!("{}: isize", p.name),
            _ => format!("{}: &str", p.name),
        })
        .collect();

    let call_args: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.cs_type.as_str() {
            "string" => format!("NativeString::from_str({})", p.name),
            "byte[]" => format!("NativeBuffer {{ ptr: {name}.as_ptr() as *mut u8, len: i32::try_from({name}.len()).expect(\"buffer too large for i32\") }}", name = p.name),
            "bool" => format!("if {} {{ 1u8 }} else {{ 0u8 }}", p.name),
            "nint" => p.name.clone(),
            _ => p.name.clone(),
        })
        .collect();

    let return_type = match m.return_type.as_str() {
        "int" => "i32",
        "long" => "i64",
        "double" => "f64",
        "string" => "String",
        "byte[]" => "Vec<u8>",
        "bool" => "bool",
        "void" => "()",
        _ => "String",
    };

    let mut call_with_cb = call_args.clone();
    call_with_cb.push("async_completion as *const () as isize".to_string());
    call_with_cb.push("context".to_string());

    let mut s = String::new();
    s.push_str(&format!(
        "    pub async fn {}(&self, {}) -> Result<{}, String> {{\n",
        fn_name,
        rust_params.join(", "),
        return_type
    ));
    s.push_str("        let (tx, rx) = oneshot::channel::<NativeResult>();\n");
    s.push_str("        let context = register_callback(tx);\n");
    s.push_str("        unsafe {\n");
    s.push_str(&format!(
        "            (self.{})({});\n",
        c_symbol,
        call_with_cb.join(", ")
    ));
    s.push_str("        }\n");
    s.push_str("        let result = rx.await.map_err(|_| \"async operation cancelled\".to_string())?;\n");
    s.push_str("        if result.is_ok == 0 {\n");
    s.push_str("            let msg = result.error_message.to_string_lossy();\n");
    s.push_str("            unsafe { (self.free_string)(result.error_message); }\n");
    s.push_str("            return Err(msg);\n");
    s.push_str("        }\n");

    match m.return_type.as_str() {
        "void" => s.push_str("        Ok(())\n"),
        "int" => s.push_str(&format!("        Ok(result.{} as i32)\n", accessor)),
        "long" => s.push_str(&format!("        Ok(result.{})\n", accessor)),
        "double" => s.push_str(&format!("        Ok(result.{})\n", accessor)),
        "bool" => s.push_str(&format!("        Ok(result.{} != 0)\n", accessor)),
        "byte[]" => {
            s.push_str("        let buf = result.buffer_value;\n");
            s.push_str("        let data = buf.to_vec();\n");
            s.push_str("        unsafe { (self.free_buffer)(buf); }\n");
            s.push_str("        Ok(data)\n");
        }
        "string" => {
            s.push_str(&format!(
                "        let s = result.{}.to_string_lossy();\n",
                accessor
            ));
            s.push_str(&format!(
                "        unsafe {{ (self.free_string)(result.{}); }}\n",
                accessor
            ));
            s.push_str("        Ok(s)\n");
        }
        _ => s.push_str("        Ok(())\n"),
    }

    s.push_str("    }\n");
    s
}

fn ffi_param_types(m: &ExportedMethod) -> String {
    m.params
        .iter()
        .map(|p| types::cs_to_rust_type(&p.cs_type).to_string())
        .collect::<Vec<_>>()
        .join(", ")
}
