// ───────────────────────────────────────────────────────────────────────────
//  EkkoJS · Pure ESM JavaScript & TypeScript runtime
//
//  License      MIT
//  Copyright    © 2026 Ampla Network LLC
//  Contact      hello@e-mc2.dev
//
//  EkkoJS is the result of the whole team's effort. Enjoy using it!
// ───────────────────────────────────────────────────────────────────────────

use crate::parser::ExportedMethod;
use crate::types;

pub fn generate_exports(methods: &[ExportedMethod], class_name: &str, include_free_fns: bool) -> String {
    let has_async = methods.iter().any(|m| m.is_async);
    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by ekko-bindgen — do not edit\n");
    out.push_str("using System;\n");
    out.push_str("using System.Runtime.InteropServices;\n");
    if has_async {
        out.push_str("using System.Threading.Tasks;\n");
    }
    out.push_str(&format!(
        "\npublic static class {}Exports\n{{\n",
        class_name
    ));

    for m in methods.iter().filter(|m| !m.is_async) {
        out.push_str(&generate_sync_export(m));
        out.push('\n');
    }

    for m in methods.iter().filter(|m| m.is_async) {
        out.push_str(&generate_async_export(m));
        out.push('\n');
    }

    if has_async {
        out.push_str("    private static unsafe void InvokeNativeCallback(nint cbPtr, NativeResult result, long context)\n");
        out.push_str("    {\n");
        out.push_str("        if (cbPtr == 0) { Console.Error.WriteLine(\"[error] null callback pointer in async completion\"); return; }\n");
        out.push_str("        try { ((delegate* unmanaged<NativeResult, long, void>)cbPtr)(result, context); }\n");
        out.push_str("        catch (Exception ex) { Console.Error.WriteLine($\"[error] callback invocation failed: {ex.Message}\"); }\n");
        out.push_str("    }\n\n");
    }

    if include_free_fns {
        out.push_str("    [UnmanagedCallersOnly(EntryPoint = \"ekko_native_free_string\")]\n");
        out.push_str("    public static void FreeString(NativeString s) => s.Free();\n\n");
        out.push_str("    [UnmanagedCallersOnly(EntryPoint = \"ekko_native_free_buffer\")]\n");
        out.push_str("    public static void FreeBuffer(NativeBuffer b) => b.Free();\n");
    }

    out.push_str("}\n");
    out
}

fn generate_sync_export(m: &ExportedMethod) -> String {
    let c_symbol = types::export_name_to_c_symbol(&m.export_name);
    let ok_method = types::cs_return_to_ok_method(&m.return_type);

    let wire_params: Vec<String> = m
        .params
        .iter()
        .map(|p| {
            let wire = types::cs_to_wire_type(&p.cs_type);
            format!("{} {}", wire, p.name)
        })
        .collect();

    let call_args: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.cs_type.as_str() {
            "string" => format!("{}.ToManaged()", p.name),
            "byte[]" => format!("{}.ToArray()", p.name),
            "nint" => p.name.clone(),
            _ => p.name.clone(),
        })
        .collect();

    let mut s = String::new();
    s.push_str(&format!(
        "    [UnmanagedCallersOnly(EntryPoint = \"{}\")]\n",
        c_symbol
    ));
    s.push_str(&format!(
        "    public static unsafe NativeResult {}({})\n",
        pascal_case(&c_symbol),
        wire_params.join(", ")
    ));
    s.push_str("    {\n");
    s.push_str("        try\n");
    s.push_str("        {\n");

    if m.return_type == "void" {
        s.push_str(&format!(
            "            {}.{}({});\n",
            m.class_name,
            m.method_name,
            call_args.join(", ")
        ));
        s.push_str(&format!("            return NativeResult.{}();\n", ok_method));
    } else {
        s.push_str(&format!(
            "            var result = {}.{}({});\n",
            m.class_name,
            m.method_name,
            call_args.join(", ")
        ));
        let result_expr = match m.return_type.as_str() {
            "bool" => "result ? 1 : 0".to_string(),
            "int" => "(long)result".to_string(),
            _ => "result".to_string(),
        };
        s.push_str(&format!(
            "            return NativeResult.{}({});\n",
            ok_method, result_expr
        ));
    }

    s.push_str("        }\n");
    s.push_str("        catch (Exception ex)\n");
    s.push_str("        {\n");
    s.push_str("            return NativeResult.Err(ex);\n");
    s.push_str("        }\n");
    s.push_str("    }\n");
    s
}

fn generate_async_export(m: &ExportedMethod) -> String {
    let c_symbol = types::export_name_to_c_symbol(&m.export_name);
    let ok_method = types::cs_return_to_ok_method(&m.return_type);

    let mut wire_params: Vec<String> = m
        .params
        .iter()
        .map(|p| {
            let wire = types::cs_to_wire_type(&p.cs_type);
            format!("{} {}", wire, p.name)
        })
        .collect();
    wire_params.push("nint callbackPtr".to_string());
    wire_params.push("long context".to_string());

    let call_args: Vec<String> = m
        .params
        .iter()
        .map(|p| match p.cs_type.as_str() {
            "string" => format!("{}.ToManaged()", p.name),
            "byte[]" => format!("{}.ToArray()", p.name),
            "nint" => p.name.clone(),
            _ => p.name.clone(),
        })
        .collect();

    let mut s = String::new();
    s.push_str(&format!(
        "    [UnmanagedCallersOnly(EntryPoint = \"{}\")]\n",
        c_symbol
    ));
    s.push_str(&format!(
        "    public static void {}({})\n",
        pascal_case(&c_symbol),
        wire_params.join(", ")
    ));
    s.push_str("    {\n");
    s.push_str("        _ = Task.Run(async () =>\n");
    s.push_str("        {\n");
    s.push_str("            NativeResult result;\n");
    s.push_str("            try\n");
    s.push_str("            {\n");

    if m.return_type == "void" {
        s.push_str(&format!(
            "                await {}.{}({});\n",
            m.class_name,
            m.method_name,
            call_args.join(", ")
        ));
        s.push_str(&format!(
            "                result = NativeResult.{}();\n",
            ok_method
        ));
    } else {
        s.push_str(&format!(
            "                var r = await {}.{}({});\n",
            m.class_name,
            m.method_name,
            call_args.join(", ")
        ));
        let result_expr = match m.return_type.as_str() {
            "bool" => "r ? 1 : 0".to_string(),
            "int" => "(long)r".to_string(),
            _ => "r".to_string(),
        };
        s.push_str(&format!(
            "                result = NativeResult.{}({});\n",
            ok_method, result_expr
        ));
    }

    s.push_str("            }\n");
    s.push_str("            catch (Exception ex)\n");
    s.push_str("            {\n");
    s.push_str("                result = NativeResult.Err(ex);\n");
    s.push_str("            }\n");
    s.push_str("            InvokeNativeCallback(callbackPtr, result, context);\n");
    s.push_str("        });\n");
    s.push_str("    }\n");
    s
}

fn pascal_case(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().to_string() + &c.as_str().to_lowercase(),
            }
        })
        .collect()
}
