// ───────────────────────────────────────────────────────────────────────────
//  EkkoJS · Pure ESM JavaScript & TypeScript runtime
//
//  License      MIT
//  Copyright    © 2026 Ampla Network LLC
//  Contact      hello@e-mc2.dev
//
//  EkkoJS is the result of the whole team's effort. Enjoy using it!
// ───────────────────────────────────────────────────────────────────────────

import{useState,useEffect,useRef,useCallback}from"@ekko/react";
function _deepMerge(t,s){if(typeof t!=="object"||t===null||Array.isArray(t))return s;if(typeof s!=="object"||s===null||Array.isArray(s))return s;var o={};for(var k in t){if(Object.prototype.hasOwnProperty.call(t,k))o[k]=t[k]}for(var k in s){if(!Object.prototype.hasOwnProperty.call(s,k))continue;if(typeof s[k]==="object"&&s[k]!==null&&!Array.isArray(s[k])&&typeof o[k]==="object"&&o[k]!==null&&!Array.isArray(o[k])){o[k]=_deepMerge(o[k],s[k])}else{o[k]=s[k]}}return o}
function atom(c){if(!c||typeof c.key!=="string"||!c.key)throw new Error("atom: key is required");if(!("default"in c))throw new Error("atom: default is required");return Object.freeze({key:c.key,default:c.default,persist:c.persist!==undefined?c.persist:true,__brand:"atom"})}
function selector(c){if(!c||typeof c.key!=="string"||!c.key)throw new Error("selector: key is required");if(typeof c.get!=="function")throw new Error("selector: get must be a function");return Object.freeze({key:c.key,get:c.get,__brand:"selector"})}
const _idb={_db:null,open(){if(this._db)return Promise.resolve(this._db);return new Promise((ok,fail)=>{const req=indexedDB.open("mimir",1);req.onupgradeneeded=()=>{req.result.createObjectStore("kv")};req.onsuccess=()=>{this._db=req.result;ok(this._db)};req.onerror=()=>fail(req.error)})},get(key){return this.open().then(db=>new Promise((ok,fail)=>{const tx=db.transaction("kv","readonly");const req=tx.objectStore("kv").get(key);req.onsuccess=()=>ok(req.result);req.onerror=()=>fail(req.error)}))},set(key,val){return this.open().then(db=>new Promise((ok,fail)=>{const tx=db.transaction("kv","readwrite");tx.objectStore("kv").put(val,key);tx.oncomplete=()=>ok();tx.onerror=()=>fail(tx.error)}))},getAll(){return this.open().then(db=>new Promise((ok,fail)=>{const tx=db.transaction("kv","readonly");const store=tx.objectStore("kv");const out={};const req=store.openCursor();req.onsuccess=()=>{const c=req.result;if(c){out[c.key]=c.value;c.continue()}else ok(out)};req.onerror=()=>fail(req.error)}))},clear(){return this.open().then(db=>new Promise((ok,fail)=>{const tx=db.transaction("kv","readwrite");tx.objectStore("kv").clear();tx.oncomplete=()=>ok();tx.onerror=()=>fail(tx.error)}))}};
class Mimir{constructor(){this._values=new Map;this._atoms=new Map;this._listeners=new Map;this._selectors=new Map;this._selectorDeps=new Map;this._sessionMode="none";this._ready=false;this._dirtyKeys=new Set;this._persistTimer=null;this._persistDelay=100}
session(mode,opts){if(mode!=="none"&&mode!=="ephemeral"&&mode!=="domain")throw new Error("Mimir.session: mode must be none, ephemeral, or domain");this._sessionMode=mode;if(opts&&typeof opts.persistDelay==="number")this._persistDelay=opts.persistDelay;if(typeof sessionStorage!=="undefined"){if(mode!=="none"){sessionStorage.setItem("__mimir_mode",mode)}else{sessionStorage.removeItem("__mimir_mode");sessionStorage.removeItem("__mimir_sid")}}if(mode==="none"){_idb.clear().catch(()=>{})}}
async _initSessionNow(){const sid=crypto.randomUUID();await _idb.set("__sessionId",sid);await _idb.set("__sessionMode",this._sessionMode);if(this._sessionMode==="ephemeral"&&typeof sessionStorage!=="undefined")sessionStorage.setItem("__mimir_sid",sid);for(const[key,cfg]of this._atoms){if(cfg.persist&&this._values.has(key)){await _idb.set(key,this._values.get(key))}}}
async initStore(sa){sa=sa||{};if(this._sessionMode==="none"){if(typeof sessionStorage!=="undefined"){const storedMode=sessionStorage.getItem("__mimir_mode");if(storedMode&&storedMode!=="none"){this._sessionMode=storedMode}}if(this._sessionMode==="none"){try{const dbMode=await _idb.get("__sessionMode");if(dbMode&&dbMode!=="none"){this._sessionMode=dbMode}}catch(e){}}}var ch=[];if(this._sessionMode==="none"){for(var key in sa){if(!Object.prototype.hasOwnProperty.call(sa,key))continue;var e=sa[key],prev=this._values.get(key);if(e&&typeof e==="object"&&e.__force){this._values.set(key,e.__value);if(!Object.is(prev,e.__value))ch.push(key)}else if(e&&typeof e==="object"&&e.__merge){if(this._values.has(key)){var m=_deepMerge(this._values.get(key),e.__value);this._values.set(key,m);if(!Object.is(prev,m))ch.push(key)}else{this._values.set(key,e.__value);ch.push(key)}}else{if(!this._values.has(key)){this._values.set(key,e);ch.push(key)}}}for(var i=0;i<ch.length;i++){this._notify(ch[i]);this._notifyDependentSelectors(ch[i])}this._ready=true;return}
const storedSid=this._sessionMode==="ephemeral"?sessionStorage.getItem("__mimir_sid"):await _idb.get("__sessionId");const dbSid=await _idb.get("__sessionId");
if(!storedSid||storedSid!==dbSid){await _idb.clear();const newSid=crypto.randomUUID();await _idb.set("__sessionId",newSid);await _idb.set("__sessionMode",this._sessionMode);if(this._sessionMode==="ephemeral")sessionStorage.setItem("__mimir_sid",newSid);for(var key in sa){if(!Object.prototype.hasOwnProperty.call(sa,key))continue;var e=sa[key];if(e&&typeof e==="object"&&e.__force){this._values.set(key,e.__value);this._dirtyKeys.add(key)}else if(e&&typeof e==="object"&&e.__merge){this._values.set(key,e.__value);this._dirtyKeys.add(key)}else{this._values.set(key,e);this._dirtyKeys.add(key)}}}
else{const persisted=await _idb.getAll();for(const key in persisted){if(key!=="__sessionId"&&key!=="__sessionMode"){this._values.set(key,persisted[key])}}for(var key in sa){if(!Object.prototype.hasOwnProperty.call(sa,key))continue;var e=sa[key];if(e&&typeof e==="object"&&e.__force){this._values.set(key,e.__value);this._dirtyKeys.add(key)}else if(e&&typeof e==="object"&&e.__merge){if(this._values.has(key)){this._values.set(key,_deepMerge(this._values.get(key),e.__value))}else{this._values.set(key,e.__value)}this._dirtyKeys.add(key)}else{if(!this._values.has(key)){this._values.set(key,e);this._dirtyKeys.add(key)}}}}
if(this._dirtyKeys.size>0&&!this._persistTimer)this._persistTimer=setTimeout(()=>this._flushPersist(),this._persistDelay);
this._ready=true}
_ensureAtom(a){if(a.__brand==="selector"){if(!this._selectors.has(a.key))this._selectors.set(a.key,a);return}if(a.__brand!=="atom")throw new Error("Mimir: expected atom or selector");if(!this._atoms.has(a.key)){this._atoms.set(a.key,a);if(!this._values.has(a.key))this._values.set(a.key,a.default)}}
_computeSelector(sel){const deps=new Set;const self=this;const getter={get(a){self._ensureAtom(a);deps.add(a.key);if(a.__brand==="selector")return self._computeSelector(a);return self._values.has(a.key)?self._values.get(a.key):a.default}};const result=sel.get(getter);this._selectorDeps.set(sel.key,deps);return result}
get(a){this._ensureAtom(a);if(a.__brand==="selector")return this._computeSelector(a);return this._values.has(a.key)?this._values.get(a.key):a.default}
set(a,v){if(a.__brand!=="atom")throw new Error("Mimir.set: can only set atoms");this._ensureAtom(a);const prev=this._values.get(a.key);const next=typeof v==="function"?v(prev):v;if(Object.is(prev,next))return;this._values.set(a.key,next);this._notify(a.key);this._notifyDependentSelectors(a.key);if(this._sessionMode!=="none"&&a.persist){this._dirtyKeys.add(a.key);if(!this._persistTimer)this._persistTimer=setTimeout(()=>this._flushPersist(),this._persistDelay)}}
reset(a){if(a.__brand!=="atom")throw new Error("Mimir.reset: can only reset atoms");this._ensureAtom(a);const prev=this._values.get(a.key);const def=a.default;if(Object.is(prev,def))return;this._values.set(a.key,def);this._notify(a.key);this._notifyDependentSelectors(a.key);if(this._sessionMode!=="none"&&a.persist){this._dirtyKeys.add(a.key);if(!this._persistTimer)this._persistTimer=setTimeout(()=>this._flushPersist(),this._persistDelay)}}
async _flushPersist(){this._persistTimer=null;if(this._dirtyKeys.size===0)return;const keys=[...this._dirtyKeys];this._dirtyKeys.clear();try{const db=await _idb.open();const tx=db.transaction("kv","readwrite");const st=tx.objectStore("kv");for(const key of keys){if(this._values.has(key))st.put(this._values.get(key),key)}await new Promise((ok,fail)=>{tx.oncomplete=ok;tx.onerror=fail})}catch(e){}}
subscribe(a,fn){if(typeof fn!=="function")throw new Error("Mimir.subscribe: callback must be a function");this._ensureAtom(a);const key=a.key;if(!this._listeners.has(key))this._listeners.set(key,new Set);this._listeners.get(key).add(fn);return()=>{const s=this._listeners.get(key);if(s){s.delete(fn);if(s.size===0)this._listeners.delete(key)}}}
async clearSession(){if(typeof sessionStorage!=="undefined"){sessionStorage.removeItem("__mimir_sid");sessionStorage.removeItem("__mimir_mode")}if(this._sessionMode!=="none")await _idb.clear();this._sessionMode="none";const keys=[];for(const[key,cfg]of this._atoms){const prev=this._values.get(key);this._values.set(key,cfg.default);if(!Object.is(prev,cfg.default))keys.push(key)}for(const key of keys){this._notify(key);this._notifyDependentSelectors(key)}}
_notify(key){const s=this._listeners.get(key);if(!s)return;const val=this._values.get(key);for(const fn of s)fn(val)}
_notifyDependentSelectors(ck){for(const[sk,deps]of this._selectorDeps){if(deps.has(ck)){const s=this._listeners.get(sk);if(s){const sel=this._selectors.get(sk);if(sel){const val=this._computeSelector(sel);for(const fn of s)fn(val)}}}}}
snapshot(){const out={};for(const[k,v]of this._values)out[k]=v;return out}
hydrate(atoms){if(!atoms||typeof atoms!=="object")return;for(const key in atoms){if(Object.prototype.hasOwnProperty.call(atoms,key))this._values.set(key,atoms[key])}}}
function createStore(){const values=new Map;const modes=new Map;const store={set(a,v,opts){if(a.__brand!=="atom")throw new Error("createStore.set: expected atom");values.set(a.key,v);if(opts&&opts.force)modes.set(a.key,"force");else if(opts&&opts.merge)modes.set(a.key,"merge");return store},dehydrate(){const out={};for(const[k,v]of values){const m=modes.get(k);if(m==="force")out[k]={__force:true,__value:v};else if(m==="merge")out[k]={__merge:true,__value:v};else out[k]=v}return out}};return store}
const mimir=new Mimir;
function useAtom(a){mimir._ensureAtom(a);const[val,setVal]=useState(()=>mimir.get(a));const ref=useRef(val);useEffect(()=>{ref.current=mimir.get(a);setVal(ref.current);return mimir.subscribe(a,v=>{ref.current=v;setVal(v)})},[a.key]);const setter=useCallback(v=>mimir.set(a,v),[a]);return[val,setter]}
function useAtomValue(readable){mimir._ensureAtom(readable);const[val,setVal]=useState(()=>mimir.get(readable));const ref=useRef(val);useEffect(()=>{ref.current=mimir.get(readable);setVal(ref.current);return mimir.subscribe(readable,v=>{ref.current=v;setVal(v)})},[readable.key]);return val}
function useSetAtom(a){if(a.__brand!=="atom")throw new Error("useSetAtom: expected atom");mimir._ensureAtom(a);return useCallback(v=>mimir.set(a,v),[a])}
export{atom,selector,mimir,createStore,Mimir,useAtom,useAtomValue,useSetAtom};
