// ───────────────────────────────────────────────────────────────────────────
//  EkkoJS · Pure ESM JavaScript & TypeScript runtime
//
//  License      MIT
//  Copyright    © 2026 Ampla Network LLC
//  Contact      hello@e-mc2.dev
//
//  EkkoJS is the result of the whole team's effort. Enjoy using it!
// ───────────────────────────────────────────────────────────────────────────

use sha2::{Sha256, Digest};

const FFI_FLOAT_MAX_ARITY: usize = 4;

fn generate_ffi_dispatch() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mut out = String::new();
    out.push_str("// @generated by build.rs — typed FFI dispatch for float-containing signatures.\n");
    out.push_str("#[allow(clippy::too_many_lines, clippy::all, unsafe_op_in_unsafe_fn)]\n");
    out.push_str("pub(crate) unsafe fn ffi_dispatch_float(ptr: *const std::ffi::c_void, arity: usize, key: u32, ret: u8, s: &[Slot]) -> Option<RawRet> {\n");
    out.push_str("    match (arity, key, ret) {\n");
    for n in 0..=FFI_FLOAT_MAX_ARITY {
        let combos = 3usize.pow(n as u32);
        for k in 0..combos {
            
            let mut digits = Vec::with_capacity(n);
            let mut kk = k;
            for _ in 0..n { digits.push(kk % 3); kk /= 3; }
            let argtypes: Vec<&str> = digits.iter().map(|d| match d { 0 => "i64", 1 => "f32", _ => "f64" }).collect();
            let callargs: Vec<String> = digits.iter().enumerate().map(|(i, d)| match d {
                0 => format!("s[{}].i()", i),
                1 => format!("s[{}].s()", i),
                _ => format!("s[{}].d()", i),
            }).collect();
            let ca = callargs.join(", ");
            for r in 0..4u8 {
                let (rettype, wrap) = match r {
                    0 => ("()".to_string(), format!("{{ f({}); Some(RawRet::Void) }}", ca)),
                    1 => ("i64".to_string(), format!("Some(RawRet::I(f({})))", ca)),
                    2 => ("f32".to_string(), format!("Some(RawRet::F32(f({})))", ca)),
                    _ => ("f64".to_string(), format!("Some(RawRet::F64(f({})))", ca)),
                };
                out.push_str(&format!(
                    "        ({}, {}, {}) => {{ let f: unsafe extern \"C\" fn({}) -> {} = ::std::mem::transmute(ptr); {} }}\n",
                    n, k, r, argtypes.join(", "), rettype, wrap
                ));
            }
        }
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n}\n");
    std::fs::write(format!("{}/ffi_dispatch.rs", out_dir), out).unwrap();
}

fn main() {
    generate_ffi_dispatch();

    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!("cargo:rustc-link-lib=advapi32");
        println!("cargo:rustc-link-lib=winmm");
        println!("cargo:rustc-link-lib=dbghelp");
    }

    

    
    println!("cargo:rerun-if-env-changed=EKKO_NATIVE_HASH");
    if let Ok(h) = std::env::var("EKKO_NATIVE_HASH") {
        let h = h.trim().to_lowercase();
        if !h.is_empty() {
            assert!(
                h.len() == 64 && h.bytes().all(|b| b.is_ascii_hexdigit()),
                "EKKO_NATIVE_HASH must be 64 lowercase hex chars (SHA-256), got {:?}", h
            );
            println!("cargo:rustc-env=EKKO_NATIVE_SHA256={}", h);
            eprintln!("  [build.rs] EkkoNative SHA-256 (override): {}...", &h[..16]);
            return;
        }
    }

    let lib_name = match std::env::var("CARGO_CFG_TARGET_OS").as_deref() {
        Ok("windows") => "EkkoNative.dll",
        Ok("macos") => "EkkoNative.dylib",
        _ => "EkkoNative.so",
    };

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let workspace_root = format!("{}/../..", manifest_dir);
    let target_dir = std::env::var("CARGO_TARGET_DIR")
        .unwrap_or_else(|_| format!("{}/target", workspace_root));

    let release_path = format!("{}/release/{}", target_dir, lib_name);
    
    let bin_path = format!("{}/_bin/{}", workspace_root, lib_name);

    let found_path = if std::path::Path::new(&release_path).exists() {
        Some(release_path.clone())
    } else if std::path::Path::new(&bin_path).exists() {
        Some(bin_path)
    } else {
        None
    };

    if let Some(ref lib_path) = found_path {
        if let Ok(bytes) = std::fs::read(lib_path) {
            let hash = Sha256::digest(&bytes);
            let hex: String = hash.iter().map(|b| format!("{:02x}", b)).collect();
            println!("cargo:rustc-env=EKKO_NATIVE_SHA256={}", hex);
            eprintln!("  [build.rs] EkkoNative SHA-256: {}... ({})", &hex[..16], lib_path);
        } else {
            println!("cargo:rustc-env=EKKO_NATIVE_SHA256=");
        }
        println!("cargo:rerun-if-changed={}", lib_path);
    } else {
        println!("cargo:rustc-env=EKKO_NATIVE_SHA256=");
        println!("cargo:rerun-if-changed={}", release_path);
    }
}
